# Auto-generated SPX (IVV) and NDX (CNDX) constituent data as of 2026-02-27

SPX_DATA = [
    {"ticker": "NVDA", "name": "NVIDIA CORP", "weight": 7.31, "price": 177.19},
    {"ticker": "AAPL", "name": "APPLE INC", "weight": 6.63, "price": 264.18},
    {"ticker": "MSFT", "name": "MICROSOFT CORP", "weight": 4.96, "price": 392.74},
    {"ticker": "AMZN", "name": "AMAZON COM INC", "weight": 3.47, "price": 210.00},
    {"ticker": "GOOGL", "name": "ALPHABET INC CLASS A", "weight": 3.08, "price": 311.76},
    {"ticker": "AVGO", "name": "BROADCOM INC", "weight": 2.56, "price": 319.55},
    {"ticker": "GOOG", "name": "ALPHABET INC CLASS C", "weight": 2.46, "price": 311.43},
    {"ticker": "META", "name": "META PLATFORMS INC CLASS A", "weight": 2.4, "price": 648.18},
    {"ticker": "TSLA", "name": "TESLA INC", "weight": 1.92, "price": 402.51},
    {"ticker": "BRKB", "name": "BERKSHIRE HATHAWAY INC CLASS B", "weight": 1.57, "price": 504.95},
    {"ticker": "LLY", "name": "ELI LILLY", "weight": 1.42, "price": 1051.99},
    {"ticker": "JPM", "name": "JPMORGAN CHASE & CO", "weight": 1.39, "price": 300.30},
    {"ticker": "XOM", "name": "EXXON MOBIL CORP", "weight": 1.09, "price": 152.50},
    {"ticker": "JNJ", "name": "JOHNSON & JOHNSON", "weight": 1.02, "price": 248.43},
    {"ticker": "WMT", "name": "WALMART INC", "weight": 0.95, "price": 127.95},
    {"ticker": "V", "name": "VISA INC CLASS A", "weight": 0.92, "price": 320.14},
    {"ticker": "MU", "name": "MICRON TECHNOLOGY INC", "weight": 0.79, "price": 412.37},
    {"ticker": "COST", "name": "COSTCO WHOLESALE CORP", "weight": 0.76, "price": 1010.79},
    {"ticker": "MA", "name": "MASTERCARD INC CLASS A", "weight": 0.72, "price": 517.21},
    {"ticker": "ABBV", "name": "ABBVIE INC", "weight": 0.7, "price": 232.08},
    {"ticker": "NFLX", "name": "NETFLIX INC", "weight": 0.69, "price": 96.24},
    {"ticker": "PG", "name": "PROCTER & GAMBLE", "weight": 0.66, "price": 167.20},
    {"ticker": "HD", "name": "HOME DEPOT INC", "weight": 0.64, "price": 380.72},
    {"ticker": "GE", "name": "GE AEROSPACE", "weight": 0.61, "price": 342.26},
    {"ticker": "CVX", "name": "CHEVRON CORP", "weight": 0.6, "price": 186.76},
    {"ticker": "CAT", "name": "CATERPILLAR INC", "weight": 0.59, "price": 742.83},
    {"ticker": "BAC", "name": "BANK OF AMERICA CORP", "weight": 0.57, "price": 49.83},
    {"ticker": "AMD", "name": "ADVANCED MICRO DEVICES INC", "weight": 0.55, "price": 200.21},
    {"ticker": "KO", "name": "COCA-COLA", "weight": 0.54, "price": 81.56},
    {"ticker": "CSCO", "name": "CISCO SYSTEMS INC", "weight": 0.53, "price": 79.46},
    {"ticker": "PLTR", "name": "PALANTIR TECHNOLOGIES INC CLASS A", "weight": 0.53, "price": 137.19},
    {"ticker": "MRK", "name": "MERCK & CO INC", "weight": 0.52, "price": 123.82},
    {"ticker": "AMAT", "name": "APPLIED MATERIAL INC", "weight": 0.5, "price": 372.30},
    {"ticker": "LRCX", "name": "LAM RESEARCH CORP", "weight": 0.5, "price": 233.89},
    {"ticker": "PM", "name": "PHILIP MORRIS INTERNATIONAL INC", "weight": 0.49, "price": 186.83},
    {"ticker": "RTX", "name": "RTX CORP", "weight": 0.46, "price": 202.62},
    {"ticker": "UNH", "name": "UNITEDHEALTH GROUP INC", "weight": 0.45, "price": 293.27},
    {"ticker": "GS", "name": "GOLDMAN SACHS GROUP INC", "weight": 0.44, "price": 855.07},
    {"ticker": "WFC", "name": "WELLS FARGO", "weight": 0.43, "price": 81.45},
    {"ticker": "ORCL", "name": "ORACLE CORP", "weight": 0.42, "price": 145.40},
    {"ticker": "MCD", "name": "MCDONALDS CORP", "weight": 0.41, "price": 341.06},
    {"ticker": "GEV", "name": "GE VERNOVA INC", "weight": 0.4, "price": 873.60},
    {"ticker": "LIN", "name": "LINDE PLC", "weight": 0.4, "price": 508.08},
    {"ticker": "PEP", "name": "PEPSICO INC", "weight": 0.39, "price": 169.74},
    {"ticker": "IBM", "name": "INTERNATIONAL BUSINESS MACHINES CO", "weight": 0.38, "price": 240.21},
    {"ticker": "VZ", "name": "VERIZON COMMUNICATIONS INC", "weight": 0.36, "price": 50.14},
    {"ticker": "AMGN", "name": "AMGEN INC", "weight": 0.35, "price": 388.16},
    {"ticker": "INTC", "name": "INTEL CORPORATION CORP", "weight": 0.35, "price": 45.61},
    {"ticker": "ABT", "name": "ABBOTT LABORATORIES", "weight": 0.34, "price": 116.35},
    {"ticker": "KLAC", "name": "KLA CORP", "weight": 0.34, "price": 1524.55},
    {"ticker": "MS", "name": "MORGAN STANLEY", "weight": 0.34, "price": 166.51},
    {"ticker": "T", "name": "AT&T INC", "weight": 0.34, "price": 28.01},
    {"ticker": "C", "name": "CITIGROUP INC", "weight": 0.33, "price": 110.19},
    {"ticker": "NEE", "name": "NEXTERA ENERGY INC", "weight": 0.33, "price": 93.77},
    {"ticker": "TMO", "name": "THERMO FISHER SCIENTIFIC INC", "weight": 0.33, "price": 521.11},
    {"ticker": "TXN", "name": "TEXAS INSTRUMENT INC", "weight": 0.33, "price": 212.11},
    {"ticker": "DIS", "name": "WALT DISNEY", "weight": 0.32, "price": 106.04},
    {"ticker": "CRM", "name": "SALESFORCE INC", "weight": 0.31, "price": 194.79},
    {"ticker": "GILD", "name": "GILEAD SCIENCES INC", "weight": 0.31, "price": 148.95},
    {"ticker": "TJX", "name": "TJX INC", "weight": 0.31, "price": 161.66},
    {"ticker": "ADI", "name": "ANALOG DEVICES INC", "weight": 0.3, "price": 355.79},
    {"ticker": "APH", "name": "AMPHENOL CORP CLASS A", "weight": 0.3, "price": 146.06},
    {"ticker": "BA", "name": "BOEING", "weight": 0.3, "price": 227.53},
    {"ticker": "ISRG", "name": "INTUITIVE SURGICAL INC", "weight": 0.3, "price": 503.51},
    {"ticker": "AXP", "name": "AMERICAN EXPRESS", "weight": 0.28, "price": 308.90},
    {"ticker": "DE", "name": "DEERE", "weight": 0.27, "price": 629.71},
    {"ticker": "PFE", "name": "PFIZER INC", "weight": 0.27, "price": 27.65},
    {"ticker": "SCHW", "name": "CHARLES SCHWAB CORP", "weight": 0.27, "price": 95.20},
    {"ticker": "UBER", "name": "UBER TECHNOLOGIES INC", "weight": 0.27, "price": 75.42},
    {"ticker": "UNP", "name": "UNION PACIFIC CORP", "weight": 0.27, "price": 264.98},
    {"ticker": "BLK", "name": "BLACKROCK INC", "weight": 0.26, "price": 1063.23},
    {"ticker": "HON", "name": "HONEYWELL INTERNATIONAL INC", "weight": 0.26, "price": 243.59},
    {"ticker": "QCOM", "name": "QUALCOMM INC", "weight": 0.26, "price": 142.36},
    {"ticker": "ETN", "name": "EATON PLC", "weight": 0.25, "price": 375.92},
    {"ticker": "LOW", "name": "LOWES COMPANIES INC", "weight": 0.25, "price": 264.57},
    {"ticker": "COP", "name": "CONOCOPHILLIPS", "weight": 0.24, "price": 113.46},
    {"ticker": "NEM", "name": "NEWMONT", "weight": 0.24, "price": 130.00},
    {"ticker": "WELL", "name": "WELLTOWER INC", "weight": 0.24, "price": 207.12},
    {"ticker": "ANET", "name": "ARISTA NETWORKS INC", "weight": 0.23, "price": 133.50},
    {"ticker": "BKNG", "name": "BOOKING HOLDINGS INC", "weight": 0.23, "price": 4239.35},
    {"ticker": "LMT", "name": "LOCKHEED MARTIN CORP", "weight": 0.23, "price": 654.63},
    {"ticker": "SPGI", "name": "S&P GLOBAL INC", "weight": 0.23, "price": 441.88},
    {"ticker": "SYK", "name": "STRYKER CORP", "weight": 0.23, "price": 387.46},
    {"ticker": "ACN", "name": "ACCENTURE PLC CLASS A", "weight": 0.22, "price": 208.72},
    {"ticker": "BMY", "name": "BRISTOL MYERS SQUIBB", "weight": 0.22, "price": 62.37},
    {"ticker": "DHR", "name": "DANAHER CORP", "weight": 0.22, "price": 210.64},
    {"ticker": "PH", "name": "PARKER-HANNIFIN CORP", "weight": 0.22, "price": 1009.18},
    {"ticker": "PLD", "name": "PROLOGIS REIT INC", "weight": 0.22, "price": 142.57},
    {"ticker": "CB", "name": "CHUBB LTD", "weight": 0.21, "price": 340.86},
    {"ticker": "COF", "name": "CAPITAL ONE FINANCIAL CORP", "weight": 0.21, "price": 195.64},
    {"ticker": "MCK", "name": "MCKESSON CORP", "weight": 0.21, "price": 986.55},
    {"ticker": "MDT", "name": "MEDTRONIC PLC", "weight": 0.21, "price": 97.66},
    {"ticker": "PGR", "name": "PROGRESSIVE CORP", "weight": 0.21, "price": 213.66},
    {"ticker": "VRTX", "name": "VERTEX PHARMACEUTICALS INC", "weight": 0.21, "price": 496.83},
    {"ticker": "APP", "name": "APPLOVIN CORP CLASS A", "weight": 0.2, "price": 434.77},
    {"ticker": "CME", "name": "CME GROUP INC CLASS A", "weight": 0.2, "price": 319.50},
    {"ticker": "GLW", "name": "CORNING INC", "weight": 0.2, "price": 150.38},
    {"ticker": "MO", "name": "ALTRIA GROUP INC", "weight": 0.2, "price": 69.04},
    {"ticker": "PANW", "name": "PALO ALTO NETWORKS INC", "weight": 0.2, "price": 148.92},
    {"ticker": "ADBE", "name": "ADOBE INC", "weight": 0.19, "price": 262.41},
    {"ticker": "BSX", "name": "BOSTON SCIENTIFIC CORP", "weight": 0.19, "price": 76.85},
    {"ticker": "CMCSA", "name": "COMCAST CORP CLASS A", "weight": 0.19, "price": 30.96},
    {"ticker": "INTU", "name": "INTUIT INC", "weight": 0.19, "price": 409.03},
    {"ticker": "NOW", "name": "SERVICENOW INC", "weight": 0.19, "price": 108.01},
    {"ticker": "SBUX", "name": "STARBUCKS CORP", "weight": 0.19, "price": 98.02},
    {"ticker": "HWM", "name": "HOWMET AEROSPACE INC", "weight": 0.18, "price": 262.53},
    {"ticker": "SO", "name": "SOUTHERN", "weight": 0.18, "price": 97.38},
    {"ticker": "TMUS", "name": "T MOBILE US INC", "weight": 0.18, "price": 217.09},
    {"ticker": "CEG", "name": "CONSTELLATION ENERGY CORP", "weight": 0.17, "price": 329.88},
    {"ticker": "CVS", "name": "CVS HEALTH CORP", "weight": 0.17, "price": 79.90},
    {"ticker": "DUK", "name": "DUKE ENERGY CORP", "weight": 0.17, "price": 130.85},
    {"ticker": "FCX", "name": "FREEPORT MCMORAN INC", "weight": 0.17, "price": 68.08},
    {"ticker": "NOC", "name": "NORTHROP GRUMMAN CORP", "weight": 0.17, "price": 724.38},
    {"ticker": "TT", "name": "TRANE TECHNOLOGIES PLC", "weight": 0.17, "price": 462.32},
    {"ticker": "CRWD", "name": "CROWDSTRIKE HOLDINGS INC CLASS A", "weight": 0.16, "price": 371.98},
    {"ticker": "EQIX", "name": "EQUINIX REIT INC", "weight": 0.16, "price": 974.26},
    {"ticker": "ICE", "name": "INTERCONTINENTAL EXCHANGE INC", "weight": 0.16, "price": 164.13},
    {"ticker": "MRSH", "name": "MARSH INC", "weight": 0.16, "price": 186.74},
    {"ticker": "SNDK", "name": "SANDISK CORP", "weight": 0.16, "price": 635.36},
    {"ticker": "WDC", "name": "WESTERN DIGITAL CORP", "weight": 0.16, "price": 279.70},
    {"ticker": "ADP", "name": "AUTOMATIC DATA PROCESSING INC", "weight": 0.15, "price": 214.36},
    {"ticker": "AMT", "name": "AMERICAN TOWER REIT CORP", "weight": 0.15, "price": 191.86},
    {"ticker": "GD", "name": "GENERAL DYNAMICS CORP", "weight": 0.15, "price": 357.05},
    {"ticker": "JCI", "name": "JOHNSON CONTROLS INTERNATIONAL PLC", "weight": 0.15, "price": 144.30},
    {"ticker": "MMM", "name": "3M", "weight": 0.15, "price": 165.32},
    {"ticker": "STX", "name": "SEAGATE TECHNOLOGY HOLDINGS PLC", "weight": 0.15, "price": 407.84},
    {"ticker": "UPS", "name": "UNITED PARCEL SERVICE INC CLASS B", "weight": 0.15, "price": 115.96},
    {"ticker": "WM", "name": "WASTE MANAGEMENT INC", "weight": 0.15, "price": 240.84},
    {"ticker": "WMB", "name": "WILLIAMS INC", "weight": 0.15, "price": 74.72},
    {"ticker": "BK", "name": "BANK OF NEW YORK MELLON CORP", "weight": 0.14, "price": 119.10},
    {"ticker": "BX", "name": "BLACKSTONE INC", "weight": 0.14, "price": 113.37},
    {"ticker": "CDNS", "name": "CADENCE DESIGN SYSTEMS INC", "weight": 0.14, "price": 301.40},
    {"ticker": "CL", "name": "COLGATE-PALMOLIVE", "weight": 0.14, "price": 99.14},
    {"ticker": "CMI", "name": "CUMMINS INC", "weight": 0.14, "price": 583.87},
    {"ticker": "CRH", "name": "CRH PUBLIC LIMITED PLC", "weight": 0.14, "price": 119.98},
    {"ticker": "CSX", "name": "CSX CORP", "weight": 0.14, "price": 42.69},
    {"ticker": "EMR", "name": "EMERSON ELECTRIC", "weight": 0.14, "price": 150.75},
    {"ticker": "FDX", "name": "FEDEX CORP", "weight": 0.14, "price": 387.00},
    {"ticker": "HCA", "name": "HCA HEALTHCARE INC", "weight": 0.14, "price": 529.70},
    {"ticker": "MSI", "name": "MOTOROLA SOLUTIONS INC", "weight": 0.14, "price": 482.26},
    {"ticker": "PNC", "name": "PNC FINANCIAL SERVICES GROUP INC", "weight": 0.14, "price": 212.35},
    {"ticker": "PWR", "name": "QUANTA SERVICES INC", "weight": 0.14, "price": 563.08},
    {"ticker": "SHW", "name": "SHERWIN WILLIAMS", "weight": 0.14, "price": 361.79},
    {"ticker": "USB", "name": "US BANCORP", "weight": 0.14, "price": 54.66},
    {"ticker": "CI", "name": "CIGNA", "weight": 0.13, "price": 289.82},
    {"ticker": "ECL", "name": "ECOLAB INC", "weight": 0.13, "price": 308.35},
    {"ticker": "ITW", "name": "ILLINOIS TOOL INC", "weight": 0.13, "price": 290.63},
    {"ticker": "MAR", "name": "MARRIOTT INTERNATIONAL INC CLASS A", "weight": 0.13, "price": 341.73},
    {"ticker": "MDLZ", "name": "MONDELEZ INTERNATIONAL INC CLASS A", "weight": 0.13, "price": 61.58},
    {"ticker": "NKE", "name": "NIKE INC CLASS B", "weight": 0.13, "price": 61.77},
    {"ticker": "ORLY", "name": "OREILLY AUTOMOTIVE INC", "weight": 0.13, "price": 93.88},
    {"ticker": "RCL", "name": "ROYAL CARIBBEAN GROUP LTD", "weight": 0.13, "price": 310.96},
    {"ticker": "REGN", "name": "REGENERON PHARMACEUTICALS INC", "weight": 0.13, "price": 781.67},
    {"ticker": "SLB", "name": "SLB NV", "weight": 0.13, "price": 51.34},
    {"ticker": "SNPS", "name": "SYNOPSYS INC", "weight": 0.13, "price": 414.00},
    {"ticker": "AEP", "name": "AMERICAN ELECTRIC POWER INC", "weight": 0.12, "price": 133.82},
    {"ticker": "AON", "name": "AON PLC CLASS A", "weight": 0.12, "price": 335.47},
    {"ticker": "COR", "name": "CENCORA INC", "weight": 0.12, "price": 372.14},
    {"ticker": "CTAS", "name": "CINTAS CORP", "weight": 0.12, "price": 201.13},
    {"ticker": "ELV", "name": "ELEVANCE HEALTH INC", "weight": 0.12, "price": 320.00},
    {"ticker": "GM", "name": "GENERAL MOTORS", "weight": 0.12, "price": 78.71},
    {"ticker": "HLT", "name": "HILTON WORLDWIDE HOLDINGS INC", "weight": 0.12, "price": 311.78},
    {"ticker": "LHX", "name": "L3HARRIS TECHNOLOGIES INC", "weight": 0.12, "price": 364.54},
    {"ticker": "MCO", "name": "MOODYS CORP", "weight": 0.12, "price": 476.56},
    {"ticker": "NSC", "name": "NORFOLK SOUTHERN CORP", "weight": 0.12, "price": 314.74},
    {"ticker": "TDG", "name": "TRANSDIGM GROUP INC", "weight": 0.12, "price": 1302.79},
    {"ticker": "TRV", "name": "TRAVELERS COMPANIES INC", "weight": 0.12, "price": 308.64},
    {"ticker": "WBD", "name": "WARNER BROS. DISCOVERY INC SERIES", "weight": 0.12, "price": 28.17},
    {"ticker": "AZO", "name": "AUTOZONE INC", "weight": 0.11, "price": 3755.58},
    {"ticker": "BKR", "name": "BAKER HUGHES CLASS A", "weight": 0.11, "price": 65.26},
    {"ticker": "DASH", "name": "DOORDASH INC CLASS A", "weight": 0.11, "price": 176.47},
    {"ticker": "EOG", "name": "EOG RESOURCES INC", "weight": 0.11, "price": 124.08},
    {"ticker": "KMI", "name": "KINDER MORGAN INC", "weight": 0.11, "price": 33.27},
    {"ticker": "PCAR", "name": "PACCAR INC", "weight": 0.11, "price": 126.09},
    {"ticker": "PSX", "name": "PHILLIPS", "weight": 0.11, "price": 154.33},
    {"ticker": "ROST", "name": "ROSS STORES INC", "weight": 0.11, "price": 205.64},
    {"ticker": "SPG", "name": "SIMON PROPERTY GROUP REIT INC", "weight": 0.11, "price": 203.85},
    {"ticker": "SRE", "name": "SEMPRA", "weight": 0.11, "price": 96.27},
    {"ticker": "TEL", "name": "TE CONNECTIVITY PLC", "weight": 0.11, "price": 230.15},
    {"ticker": "TFC", "name": "TRUIST FINANCIAL CORP", "weight": 0.11, "price": 49.31},
    {"ticker": "VLO", "name": "VALERO ENERGY CORP", "weight": 0.11, "price": 204.64},
    {"ticker": "ABNB", "name": "AIRBNB INC CLASS A", "weight": 0.1, "price": 135.11},
    {"ticker": "AJG", "name": "ARTHUR J GALLAGHER", "weight": 0.1, "price": 228.20},
    {"ticker": "ALL", "name": "ALLSTATE CORP", "weight": 0.1, "price": 213.44},
    {"ticker": "APD", "name": "AIR PRODUCTS AND CHEMICALS INC", "weight": 0.1, "price": 275.67},
    {"ticker": "DLR", "name": "DIGITAL REALTY TRUST REIT INC", "weight": 0.1, "price": 177.20},
    {"ticker": "HOOD", "name": "ROBINHOOD MARKETS INC CLASS A", "weight": 0.1, "price": 75.85},
    {"ticker": "KKR", "name": "KKR AND CO INC", "weight": 0.1, "price": 87.68},
    {"ticker": "MNST", "name": "MONSTER BEVERAGE CORP", "weight": 0.1, "price": 85.30},
    {"ticker": "MPC", "name": "MARATHON PETROLEUM CORP", "weight": 0.1, "price": 198.21},
    {"ticker": "NXPI", "name": "NXP SEMICONDUCTORS NV", "weight": 0.1, "price": 227.01},
    {"ticker": "O", "name": "REALTY INCOME REIT CORP", "weight": 0.1, "price": 67.00},
    {"ticker": "ZTS", "name": "ZOETIS INC CLASS A", "weight": 0.1, "price": 131.10},
    {"ticker": "ADSK", "name": "AUTODESK INC", "weight": 0.09, "price": 245.87},
    {"ticker": "AFL", "name": "AFLAC INC", "weight": 0.09, "price": 112.93},
    {"ticker": "AME", "name": "AMETEK INC", "weight": 0.09, "price": 239.22},
    {"ticker": "BDX", "name": "BECTON DICKINSON", "weight": 0.09, "price": 176.48},
    {"ticker": "CAH", "name": "CARDINAL HEALTH INC", "weight": 0.09, "price": 229.23},
    {"ticker": "CARR", "name": "CARRIER GLOBAL CORP", "weight": 0.09, "price": 64.40},
    {"ticker": "CTVA", "name": "CORTEVA INC", "weight": 0.09, "price": 79.94},
    {"ticker": "D", "name": "DOMINION ENERGY INC", "weight": 0.09, "price": 63.14},
    {"ticker": "EW", "name": "EDWARDS LIFESCIENCES CORP", "weight": 0.09, "price": 86.47},
    {"ticker": "F", "name": "FORD MOTOR CO", "weight": 0.09, "price": 14.09},
    {"ticker": "FAST", "name": "FASTENAL", "weight": 0.09, "price": 46.04},
    {"ticker": "FIX", "name": "COMFORT SYSTEMS USA INC", "weight": 0.09, "price": 1429.37},
    {"ticker": "GWW", "name": "WW GRAINGER INC", "weight": 0.09, "price": 1144.73},
    {"ticker": "IDXX", "name": "IDEXX LABORATORIES INC", "weight": 0.09, "price": 656.73},
    {"ticker": "KEYS", "name": "KEYSIGHT TECHNOLOGIES INC", "weight": 0.09, "price": 307.33},
    {"ticker": "MPWR", "name": "MONOLITHIC POWER SYSTEMS INC", "weight": 0.09, "price": 1142.74},
    {"ticker": "OKE", "name": "ONEOK INC", "weight": 0.09, "price": 82.77},
    {"ticker": "TER", "name": "TERADYNE INC", "weight": 0.09, "price": 320.03},
    {"ticker": "TGT", "name": "TARGET CORP", "weight": 0.09, "price": 113.79},
    {"ticker": "TRGP", "name": "TARGA RESOURCES CORP", "weight": 0.09, "price": 235.80},
    {"ticker": "URI", "name": "UNITED RENTALS INC", "weight": 0.09, "price": 840.00},
    {"ticker": "VST", "name": "VISTRA CORP", "weight": 0.09, "price": 173.89},
    {"ticker": "APO", "name": "APOLLO GLOBAL MANAGEMENT INC", "weight": 0.08, "price": 104.60},
    {"ticker": "CIEN", "name": "CIENA CORP", "weight": 0.08, "price": 348.70},
    {"ticker": "CMG", "name": "CHIPOTLE MEXICAN GRILL INC", "weight": 0.08, "price": 37.22},
    {"ticker": "CVNA", "name": "CARVANA CLASS A", "weight": 0.08, "price": 334.16},
    {"ticker": "DELL", "name": "DELL TECHNOLOGIES INC CLASS C", "weight": 0.08, "price": 148.08},
    {"ticker": "EA", "name": "ELECTRONIC ARTS INC", "weight": 0.08, "price": 200.57},
    {"ticker": "ETR", "name": "ENTERGY CORP", "weight": 0.08, "price": 107.11},
    {"ticker": "EXC", "name": "EXELON CORP", "weight": 0.08, "price": 49.05},
    {"ticker": "FITB", "name": "FIFTH THIRD BANCORP", "weight": 0.08, "price": 49.47},
    {"ticker": "FTNT", "name": "FORTINET INC", "weight": 0.08, "price": 79.03},
    {"ticker": "PSA", "name": "PUBLIC STORAGE REIT", "weight": 0.08, "price": 307.06},
    {"ticker": "ROK", "name": "ROCKWELL AUTOMATION INC", "weight": 0.08, "price": 407.45},
    {"ticker": "RSG", "name": "REPUBLIC SERVICES INC", "weight": 0.08, "price": 229.00},
    {"ticker": "WAB", "name": "WESTINGHOUSE AIR BRAKE TECHNOLOGIE", "weight": 0.08, "price": 263.95},
    {"ticker": "XEL", "name": "XCEL ENERGY INC", "weight": 0.08, "price": 83.36},
    {"ticker": "YUM", "name": "YUM BRANDS INC", "weight": 0.08, "price": 168.16},
    {"ticker": "AIG", "name": "AMERICAN INTERNATIONAL GROUP INC", "weight": 0.07, "price": 80.49},
    {"ticker": "AMP", "name": "AMERIPRISE FINANCE INC", "weight": 0.07, "price": 470.12},
    {"ticker": "AXON", "name": "AXON ENTERPRISE INC", "weight": 0.07, "price": 542.40},
    {"ticker": "CBRE", "name": "CBRE GROUP INC CLASS A", "weight": 0.07, "price": 147.66},
    {"ticker": "CCI", "name": "CROWN CASTLE INC", "weight": 0.07, "price": 89.54},
    {"ticker": "COIN", "name": "COINBASE GLOBAL INC CLASS A", "weight": 0.07, "price": 175.85},
    {"ticker": "DAL", "name": "DELTA AIR LINES INC", "weight": 0.07, "price": 65.70},
    {"ticker": "DHI", "name": "D R HORTON INC", "weight": 0.07, "price": 160.39},
    {"ticker": "EBAY", "name": "EBAY INC", "weight": 0.07, "price": 90.86},
    {"ticker": "ED", "name": "CONSOLIDATED EDISON INC", "weight": 0.07, "price": 112.52},
    {"ticker": "EQT", "name": "EQT CORP", "weight": 0.07, "price": 61.42},
    {"ticker": "GEHC", "name": "GE HEALTHCARE TECHNOLOGIES INC", "weight": 0.07, "price": 84.27},
    {"ticker": "GRMN", "name": "GARMIN LTD", "weight": 0.07, "price": 252.83},
    {"ticker": "HIG", "name": "HARTFORD INSURANCE GROUP INC", "weight": 0.07, "price": 140.23},
    {"ticker": "KDP", "name": "KEURIG DR PEPPER INC", "weight": 0.07, "price": 30.28},
    {"ticker": "KR", "name": "KROGER", "weight": 0.07, "price": 68.24},
    {"ticker": "MCHP", "name": "MICROCHIP TECHNOLOGY INC", "weight": 0.07, "price": 74.64},
    {"ticker": "MET", "name": "METLIFE INC", "weight": 0.07, "price": 72.07},
    {"ticker": "MLM", "name": "MARTIN MARIETTA MATERIALS INC", "weight": 0.07, "price": 675.74},
    {"ticker": "MSCI", "name": "MSCI INC", "weight": 0.07, "price": 571.83},
    {"ticker": "NDAQ", "name": "NASDAQ INC", "weight": 0.07, "price": 87.58},
    {"ticker": "NUE", "name": "NUCOR CORP", "weight": 0.07, "price": 176.88},
    {"ticker": "PCG", "name": "PG&E CORP", "weight": 0.07, "price": 19.00},
    {"ticker": "PEG", "name": "PUBLIC SERVICE ENTERPRISE GROUP IN", "weight": 0.07, "price": 86.07},
    {"ticker": "PYPL", "name": "PAYPAL HOLDINGS INC", "weight": 0.07, "price": 46.21},
    {"ticker": "SYY", "name": "SYSCO CORP", "weight": 0.07, "price": 91.16},
    {"ticker": "VMC", "name": "VULCAN MATERIALS", "weight": 0.07, "price": 310.00},
    {"ticker": "VTR", "name": "VENTAS REIT INC", "weight": 0.07, "price": 86.16},
    {"ticker": "A", "name": "AGILENT TECHNOLOGIES INC", "weight": 0.06, "price": 121.38},
    {"ticker": "ACGL", "name": "ARCH CAPITAL GROUP LTD", "weight": 0.06, "price": 100.15},
    {"ticker": "ADM", "name": "ARCHER DANIELS MIDLAND", "weight": 0.06, "price": 69.04},
    {"ticker": "CCL", "name": "CARNIVAL CORP", "weight": 0.06, "price": 31.55},
    {"ticker": "CPRT", "name": "COPART INC", "weight": 0.06, "price": 38.09},
    {"ticker": "DDOG", "name": "DATADOG INC CLASS A", "weight": 0.06, "price": 111.96},
    {"ticker": "DG", "name": "DOLLAR GENERAL CORP", "weight": 0.06, "price": 156.24},
    {"ticker": "EME", "name": "EMCOR GROUP INC", "weight": 0.06, "price": 724.62},
    {"ticker": "FANG", "name": "DIAMONDBACK ENERGY INC", "weight": 0.06, "price": 174.08},
    {"ticker": "FICO", "name": "FAIR ISAAC CORP", "weight": 0.06, "price": 1409.36},
    {"ticker": "FISV", "name": "FISERV INC", "weight": 0.06, "price": 62.29},
    {"ticker": "HBAN", "name": "HUNTINGTON BANCSHARES INC", "weight": 0.06, "price": 16.80},
    {"ticker": "HSY", "name": "HERSHEY FOODS", "weight": 0.06, "price": 236.28},
    {"ticker": "IR", "name": "INGERSOLL RAND INC", "weight": 0.06, "price": 94.14},
    {"ticker": "KMB", "name": "KIMBERLY CLARK CORP", "weight": 0.06, "price": 111.44},
    {"ticker": "KVUE", "name": "KENVUE INC", "weight": 0.06, "price": 19.12},
    {"ticker": "MTB", "name": "M&T BANK CORP", "weight": 0.06, "price": 215.48},
    {"ticker": "NRG", "name": "NRG ENERGY INC", "weight": 0.06, "price": 178.96},
    {"ticker": "ODFL", "name": "OLD DOMINION FREIGHT LINE INC", "weight": 0.06, "price": 203.05},
    {"ticker": "OTIS", "name": "OTIS WORLDWIDE CORP", "weight": 0.06, "price": 92.56},
    {"ticker": "OXY", "name": "OCCIDENTAL PETROLEUM CORP", "weight": 0.06, "price": 53.08},
    {"ticker": "PRU", "name": "PRUDENTIAL FINANCIAL INC", "weight": 0.06, "price": 98.38},
    {"ticker": "RMD", "name": "RESMED INC", "weight": 0.06, "price": 256.26},
    {"ticker": "ROP", "name": "ROPER TECHNOLOGIES INC", "weight": 0.06, "price": 349.73},
    {"ticker": "STT", "name": "STATE STREET CORP", "weight": 0.06, "price": 128.62},
    {"ticker": "TTWO", "name": "TAKE TWO INTERACTIVE SOFTWARE INC", "weight": 0.06, "price": 211.48},
    {"ticker": "UAL", "name": "UNITED AIRLINES HOLDINGS INC", "weight": 0.06, "price": 106.30},
    {"ticker": "WEC", "name": "WEC ENERGY GROUP INC", "weight": 0.06, "price": 116.96},
    {"ticker": "XYZ", "name": "BLOCK INC CLASS A", "weight": 0.06, "price": 63.70},
    {"ticker": "AEE", "name": "AMEREN CORP", "weight": 0.05, "price": 113.28},
    {"ticker": "ATO", "name": "ATMOS ENERGY CORP", "weight": 0.05, "price": 186.79},
    {"ticker": "AWK", "name": "AMERICAN WATER WORKS INC", "weight": 0.05, "price": 136.03},
    {"ticker": "BIIB", "name": "BIOGEN INC", "weight": 0.05, "price": 191.82},
    {"ticker": "CBOE", "name": "CBOE GLOBAL MARKETS INC", "weight": 0.05, "price": 299.72},
    {"ticker": "CNP", "name": "CENTERPOINT ENERGY INC", "weight": 0.05, "price": 43.50},
    {"ticker": "CTSH", "name": "COGNIZANT TECHNOLOGY SOLUTIONS COR", "weight": 0.05, "price": 64.43},
    {"ticker": "DOV", "name": "DOVER CORP", "weight": 0.05, "price": 225.50},
    {"ticker": "DTE", "name": "DTE ENERGY", "weight": 0.05, "price": 148.24},
    {"ticker": "DVN", "name": "DEVON ENERGY CORP", "weight": 0.05, "price": 43.53},
    {"ticker": "DXCM", "name": "DEXCOM INC", "weight": 0.05, "price": 73.43},
    {"ticker": "EIX", "name": "EDISON INTERNATIONAL", "weight": 0.05, "price": 74.74},
    {"ticker": "EL", "name": "ESTEE LAUDER INC CLASS A", "weight": 0.05, "price": 109.47},
    {"ticker": "ES", "name": "EVERSOURCE ENERGY", "weight": 0.05, "price": 76.21},
    {"ticker": "EXR", "name": "EXTRA SPACE STORAGE REIT INC", "weight": 0.05, "price": 151.03},
    {"ticker": "FE", "name": "FIRSTENERGY CORP", "weight": 0.05, "price": 51.16},
    {"ticker": "HAL", "name": "HALLIBURTON", "weight": 0.05, "price": 36.00},
    {"ticker": "HPE", "name": "HEWLETT PACKARD ENTERPRISE", "weight": 0.05, "price": 21.47},
    {"ticker": "HUBB", "name": "HUBBELL INC", "weight": 0.05, "price": 511.63},
    {"ticker": "IBKR", "name": "INTERACTIVE BROKERS GROUP INC CLAS", "weight": 0.05, "price": 71.19},
    {"ticker": "IQV", "name": "IQVIA HOLDINGS INC", "weight": 0.05, "price": 178.81},
    {"ticker": "IRM", "name": "IRON MOUNTAIN INC", "weight": 0.05, "price": 108.33},
    {"ticker": "JBL", "name": "JABIL INC", "weight": 0.05, "price": 264.99},
    {"ticker": "MTD", "name": "METTLER TOLEDO INC", "weight": 0.05, "price": 1366.69},
    {"ticker": "NTRS", "name": "NORTHERN TRUST CORP", "weight": 0.05, "price": 143.09},
    {"ticker": "OMC", "name": "OMNICOM GROUP INC", "weight": 0.05, "price": 85.29},
    {"ticker": "ON", "name": "ON SEMICONDUCTOR CORP", "weight": 0.05, "price": 66.48},
    {"ticker": "PAYX", "name": "PAYCHEX INC", "weight": 0.05, "price": 93.65},
    {"ticker": "PHM", "name": "PULTEGROUP INC", "weight": 0.05, "price": 137.20},
    {"ticker": "PPG", "name": "PPG INDUSTRIES INC", "weight": 0.05, "price": 123.27},
    {"ticker": "PPL", "name": "PPL CORP", "weight": 0.05, "price": 38.98},
    {"ticker": "Q", "name": "QNITY ELECTRONICS INC", "weight": 0.05, "price": 126.76},
    {"ticker": "RJF", "name": "RAYMOND JAMES INC", "weight": 0.05, "price": 153.08},
    {"ticker": "STLD", "name": "STEEL DYNAMICS INC", "weight": 0.05, "price": 193.13},
    {"ticker": "TDY", "name": "TELEDYNE TECHNOLOGIES INC", "weight": 0.05, "price": 681.10},
    {"ticker": "TPL", "name": "TEXAS PACIFIC LAND CORP", "weight": 0.05, "price": 523.69},
    {"ticker": "TPR", "name": "TAPESTRY INC", "weight": 0.05, "price": 155.47},
    {"ticker": "TSCO", "name": "TRACTOR SUPPLY", "weight": 0.05, "price": 51.84},
    {"ticker": "ULTA", "name": "ULTA BEAUTY INC", "weight": 0.05, "price": 684.79},
    {"ticker": "VICI", "name": "VICI PPTYS INC", "weight": 0.05, "price": 30.21},
    {"ticker": "VRSK", "name": "VERISK ANALYTICS INC", "weight": 0.05, "price": 207.57},
    {"ticker": "WAT", "name": "WATERS CORP", "weight": 0.05, "price": 319.38},
    {"ticker": "WDAY", "name": "WORKDAY INC CLASS A", "weight": 0.05, "price": 133.76},
    {"ticker": "WTW", "name": "WILLIS TOWERS WATSON PLC", "weight": 0.05, "price": 305.17},
    {"ticker": "XYL", "name": "XYLEM INC", "weight": 0.05, "price": 129.56},
    {"ticker": "ALB", "name": "ALBEMARLE CORP", "weight": 0.04, "price": 178.67},
    {"ticker": "AMCR", "name": "AMCOR PLC", "weight": 0.04, "price": 48.43},
    {"ticker": "ARES", "name": "ARES MANAGEMENT CORP CLASS A", "weight": 0.04, "price": 112.01},
    {"ticker": "AVB", "name": "AVALONBAY COMMUNITIES REIT INC", "weight": 0.04, "price": 177.23},
    {"ticker": "BR", "name": "BROADRIDGE FINANCIAL SOLUTIONS INC", "weight": 0.04, "price": 185.87},
    {"ticker": "BRO", "name": "BROWN & BROWN INC", "weight": 0.04, "price": 71.82},
    {"ticker": "CFG", "name": "CITIZENS FINANCIAL GROUP INC", "weight": 0.04, "price": 60.19},
    {"ticker": "CHD", "name": "CHURCH AND DWIGHT INC", "weight": 0.04, "price": 104.86},
    {"ticker": "CHRW", "name": "CH ROBINSON WORLDWIDE INC", "weight": 0.04, "price": 185.25},
    {"ticker": "CHTR", "name": "CHARTER COMMUNICATIONS INC CLASS A", "weight": 0.04, "price": 234.63},
    {"ticker": "CINF", "name": "CINCINNATI FINANCIAL CORP", "weight": 0.04, "price": 163.98},
    {"ticker": "CMS", "name": "CMS ENERGY CORP", "weight": 0.04, "price": 78.07},
    {"ticker": "CNC", "name": "CENTENE CORP", "weight": 0.04, "price": 44.88},
    {"ticker": "CPAY", "name": "CORPAY INC", "weight": 0.04, "price": 325.10},
    {"ticker": "CTRA", "name": "COTERRA ENERGY INC", "weight": 0.04, "price": 30.59},
    {"ticker": "DD", "name": "DUPONT DE NEMOURS INC", "weight": 0.04, "price": 49.84},
    {"ticker": "DGX", "name": "QUEST DIAGNOSTICS INC", "weight": 0.04, "price": 211.91},
    {"ticker": "DLTR", "name": "DOLLAR TREE INC", "weight": 0.04, "price": 126.48},
    {"ticker": "DOW", "name": "DOW INC", "weight": 0.04, "price": 30.73},
    {"ticker": "DRI", "name": "DARDEN RESTAURANTS INC", "weight": 0.04, "price": 213.85},
    {"ticker": "EFX", "name": "EQUIFAX INC", "weight": 0.04, "price": 208.96},
    {"ticker": "EQR", "name": "EQUITY RESIDENTIAL REIT", "weight": 0.04, "price": 63.21},
    {"ticker": "EXE", "name": "EXPAND ENERGY CORP", "weight": 0.04, "price": 107.92},
    {"ticker": "EXPE", "name": "EXPEDIA GROUP INC", "weight": 0.04, "price": 215.69},
    {"ticker": "FIS", "name": "FIDELITY NATIONAL INFORMATION SERV", "weight": 0.04, "price": 50.96},
    {"ticker": "FSLR", "name": "FIRST SOLAR INC", "weight": 0.04, "price": 197.20},
    {"ticker": "GIS", "name": "GENERAL MILLS INC", "weight": 0.04, "price": 45.23},
    {"ticker": "HUM", "name": "HUMANA INC", "weight": 0.04, "price": 190.54},
    {"ticker": "IFF", "name": "INTERNATIONAL FLAVORS & FRAGRANCES", "weight": 0.04, "price": 82.23},
    {"ticker": "IP", "name": "INTERNATIONAL PAPER", "weight": 0.04, "price": 43.55},
    {"ticker": "KHC", "name": "KRAFT HEINZ", "weight": 0.04, "price": 24.61},
    {"ticker": "LDOS", "name": "LEIDOS HOLDINGS INC", "weight": 0.04, "price": 175.10},
    {"ticker": "LEN", "name": "LENNAR A CORP CLASS A", "weight": 0.04, "price": 114.36},
    {"ticker": "LH", "name": "LABCORP HOLDINGS INC", "weight": 0.04, "price": 289.12},
    {"ticker": "LUV", "name": "SOUTHWEST AIRLINES", "weight": 0.04, "price": 49.26},
    {"ticker": "LYV", "name": "LIVE NATION ENTERTAINMENT INC", "weight": 0.04, "price": 162.14},
    {"ticker": "NI", "name": "NISOURCE INC", "weight": 0.04, "price": 47.30},
    {"ticker": "NVR", "name": "NVR INC", "weight": 0.04, "price": 7517.79},
    {"ticker": "PKG", "name": "PACKAGING CORP OF AMERICA", "weight": 0.04, "price": 232.14},
    {"ticker": "RF", "name": "REGIONS FINANCIAL CORP", "weight": 0.04, "price": 27.57},
    {"ticker": "SBAC", "name": "SBA COMMUNICATIONS REIT CORP CLASS", "weight": 0.04, "price": 201.16},
    {"ticker": "STE", "name": "STERIS", "weight": 0.04, "price": 252.35},
    {"ticker": "STZ", "name": "CONSTELLATION BRANDS INC CLASS A", "weight": 0.04, "price": 157.86},
    {"ticker": "SW", "name": "SMURFIT WESTROCK PLC", "weight": 0.04, "price": 47.01},
    {"ticker": "SYF", "name": "SYNCHRONY FINANCIAL", "weight": 0.04, "price": 69.11},
    {"ticker": "TROW", "name": "T ROWE PRICE GROUP INC", "weight": 0.04, "price": 94.63},
    {"ticker": "VLTO", "name": "VERALTO CORP", "weight": 0.04, "price": 97.43},
    {"ticker": "WRB", "name": "WR BERKLEY CORP", "weight": 0.04, "price": 71.70},
    {"ticker": "WSM", "name": "WILLIAMS SONOMA INC", "weight": 0.04, "price": 205.65},
    {"ticker": "APTV", "name": "APTIV PLC", "weight": 0.03, "price": 73.54},
    {"ticker": "AVY", "name": "AVERY DENNISON CORP", "weight": 0.03, "price": 196.35},
    {"ticker": "BALL", "name": "BALL CORP", "weight": 0.03, "price": 66.93},
    {"ticker": "BG", "name": "BUNGE GLOBAL", "weight": 0.03, "price": 120.65},
    {"ticker": "CDW", "name": "CDW CORP", "weight": 0.03, "price": 122.64},
    {"ticker": "CF", "name": "CF INDUSTRIES HOLDINGS INC", "weight": 0.03, "price": 99.54},
    {"ticker": "CLX", "name": "CLOROX", "weight": 0.03, "price": 127.16},
    {"ticker": "COO", "name": "COOPER INC", "weight": 0.03, "price": 83.67},
    {"ticker": "CSGP", "name": "COSTAR GROUP INC", "weight": 0.03, "price": 44.63},
    {"ticker": "DECK", "name": "DECKERS OUTDOOR CORP", "weight": 0.03, "price": 117.27},
    {"ticker": "ESS", "name": "ESSEX PROPERTY TRUST REIT INC", "weight": 0.03, "price": 255.11},
    {"ticker": "EVRG", "name": "EVERGY INC", "weight": 0.03, "price": 83.66},
    {"ticker": "EXPD", "name": "EXPEDITORS INTERNATIONAL OF WASHIN", "weight": 0.03, "price": 145.03},
    {"ticker": "FFIV", "name": "F5 INC", "weight": 0.03, "price": 271.36},
    {"ticker": "FTV", "name": "FORTIVE CORP", "weight": 0.03, "price": 59.20},
    {"ticker": "GPC", "name": "GENUINE PARTS", "weight": 0.03, "price": 119.26},
    {"ticker": "GPN", "name": "GLOBAL PAYMENTS INC", "weight": 0.03, "price": 76.46},
    {"ticker": "HII", "name": "HUNTINGTON INGALLS INDUSTRIES INC", "weight": 0.03, "price": 444.52},
    {"ticker": "HOLX", "name": "HOLOGIC INC", "weight": 0.03, "price": 75.36},
    {"ticker": "HPQ", "name": "HP INC", "weight": 0.03, "price": 18.99},
    {"ticker": "IEX", "name": "IDEX CORP", "weight": 0.03, "price": 209.47},
    {"ticker": "INCY", "name": "INCYTE CORP", "weight": 0.03, "price": 101.27},
    {"ticker": "INVH", "name": "INVITATION HOMES INC", "weight": 0.03, "price": 26.34},
    {"ticker": "J", "name": "JACOBS SOLUTIONS INC", "weight": 0.03, "price": 137.86},
    {"ticker": "JBHT", "name": "JB HUNT TRANSPORT SERVICES INC", "weight": 0.03, "price": 233.41},
    {"ticker": "KEY", "name": "KEYCORP", "weight": 0.03, "price": 20.74},
    {"ticker": "KIM", "name": "KIMCO REALTY REIT CORP", "weight": 0.03, "price": 23.55},
    {"ticker": "L", "name": "LOEWS CORP", "weight": 0.03, "price": 110.02},
    {"ticker": "LII", "name": "LENNOX INTERNATIONAL INC", "weight": 0.03, "price": 569.94},
    {"ticker": "LNT", "name": "ALLIANT ENERGY CORP", "weight": 0.03, "price": 72.34},
    {"ticker": "LULU", "name": "LULULEMON ATHLETICA INC", "weight": 0.03, "price": 185.17},
    {"ticker": "LVS", "name": "LAS VEGAS SANDS CORP", "weight": 0.03, "price": 56.72},
    {"ticker": "LYB", "name": "LYONDELLBASELL INDUSTRIES NV CLASS", "weight": 0.03, "price": 56.83},
    {"ticker": "MAA", "name": "MID AMERICA APARTMENT COMMUNITIES", "weight": 0.03, "price": 133.86},
    {"ticker": "MAS", "name": "MASCO CORP", "weight": 0.03, "price": 71.62},
    {"ticker": "MKC", "name": "MCCORMICK & CO NON-VOTING INC", "weight": 0.03, "price": 71.04},
    {"ticker": "MRNA", "name": "MODERNA INC", "weight": 0.03, "price": 53.57},
    {"ticker": "NDSN", "name": "NORDSON CORP", "weight": 0.03, "price": 293.44},
    {"ticker": "NTAP", "name": "NETAPP INC", "weight": 0.03, "price": 99.03},
    {"ticker": "PFG", "name": "PRINCIPAL FINANCIAL GROUP INC", "weight": 0.03, "price": 95.42},
    {"ticker": "PNR", "name": "PENTAIR", "weight": 0.03, "price": 99.19},
    {"ticker": "PODD", "name": "INSULET CORP", "weight": 0.03, "price": 246.61},
    {"ticker": "PTC", "name": "PTC INC", "weight": 0.03, "price": 156.59},
    {"ticker": "ROL", "name": "ROLLINS INC", "weight": 0.03, "price": 60.89},
    {"ticker": "SMCI", "name": "SUPER MICRO COMPUTER INC", "weight": 0.03, "price": 32.39},
    {"ticker": "SNA", "name": "SNAP ON INC", "weight": 0.03, "price": 385.22},
    {"ticker": "TKO", "name": "TKO GROUP HOLDINGS INC CLASS A", "weight": 0.03, "price": 223.87},
    {"ticker": "TRMB", "name": "TRIMBLE INC", "weight": 0.03, "price": 66.87},
    {"ticker": "TSN", "name": "TYSON FOODS INC CLASS A", "weight": 0.03, "price": 64.99},
    {"ticker": "TXT", "name": "TEXTRON INC", "weight": 0.03, "price": 98.65},
    {"ticker": "TYL", "name": "TYLER TECHNOLOGIES INC", "weight": 0.03, "price": 354.69},
    {"ticker": "VRSN", "name": "VERISIGN INC", "weight": 0.03, "price": 227.94},
    {"ticker": "VTRS", "name": "VIATRIS INC", "weight": 0.03, "price": 14.93},
    {"ticker": "WST", "name": "WEST PHARMACEUTICAL SERVICES INC", "weight": 0.03, "price": 254.34},
    {"ticker": "WY", "name": "WEYERHAEUSER REIT", "weight": 0.03, "price": 24.53},
    {"ticker": "ZBH", "name": "ZIMMER BIOMET HOLDINGS INC", "weight": 0.03, "price": 98.44},
    {"ticker": "AES", "name": "AES CORP", "weight": 0.02, "price": 17.28},
    {"ticker": "AIZ", "name": "ASSURANT INC", "weight": 0.02, "price": 229.59},
    {"ticker": "AKAM", "name": "AKAMAI TECHNOLOGIES INC", "weight": 0.02, "price": 98.39},
    {"ticker": "ALGN", "name": "ALIGN TECHNOLOGY INC", "weight": 0.02, "price": 190.10},
    {"ticker": "ALLE", "name": "ALLEGION PLC", "weight": 0.02, "price": 161.15},
    {"ticker": "AOS", "name": "A O SMITH CORP", "weight": 0.02, "price": 78.00},
    {"ticker": "APA", "name": "APA CORP", "weight": 0.02, "price": 30.37},
    {"ticker": "BAX", "name": "BAXTER INTERNATIONAL INC", "weight": 0.02, "price": 20.37},
    {"ticker": "BBY", "name": "BEST BUY INC", "weight": 0.02, "price": 61.97},
    {"ticker": "BLDR", "name": "BUILDERS FIRSTSOURCE INC", "weight": 0.02, "price": 104.29},
    {"ticker": "CAG", "name": "CONAGRA BRANDS INC", "weight": 0.02, "price": 19.25},
    {"ticker": "CPT", "name": "CAMDEN PROPERTY TRUST REIT", "weight": 0.02, "price": 108.34},
    {"ticker": "DOC", "name": "HEALTHPEAK PROPERTIES INC", "weight": 0.02, "price": 17.68},
    {"ticker": "DPZ", "name": "DOMINOS PIZZA INC", "weight": 0.02, "price": 402.51},
    {"ticker": "EG", "name": "EVEREST GROUP LTD", "weight": 0.02, "price": 335.49},
    {"ticker": "FOXA", "name": "FOX CORP CLASS A", "weight": 0.02, "price": 56.34},
    {"ticker": "GDDY", "name": "GODADDY INC CLASS A", "weight": 0.02, "price": 87.16},
    {"ticker": "GEN", "name": "GEN DIGITAL INC", "weight": 0.02, "price": 22.57},
    {"ticker": "GL", "name": "GLOBE LIFE INC", "weight": 0.02, "price": 145.26},
    {"ticker": "GNRC", "name": "GENERAC HOLDINGS INC", "weight": 0.02, "price": 225.37},
    {"ticker": "HAS", "name": "HASBRO INC", "weight": 0.02, "price": 99.59},
    {"ticker": "HST", "name": "HOST HOTELS & RESORTS REIT INC", "weight": 0.02, "price": 19.59},
    {"ticker": "IT", "name": "GARTNER INC", "weight": 0.02, "price": 157.20},
    {"ticker": "IVZ", "name": "INVESCO LTD", "weight": 0.02, "price": 26.26},
    {"ticker": "JKHY", "name": "JACK HENRY AND ASSOCIATES INC", "weight": 0.02, "price": 162.46},
    {"ticker": "MOS", "name": "MOSAIC", "weight": 0.02, "price": 27.84},
    {"ticker": "NCLH", "name": "NORWEGIAN CRUISE LINE HOLDINGS LTD", "weight": 0.02, "price": 24.79},
    {"ticker": "NWSA", "name": "NEWS CORP CLASS A", "weight": 0.02, "price": 24.29},
    {"ticker": "PNW", "name": "PINNACLE WEST CORP", "weight": 0.02, "price": 100.30},
    {"ticker": "REG", "name": "REGENCY CENTERS REIT CORP", "weight": 0.02, "price": 79.00},
    {"ticker": "RL", "name": "RALPH LAUREN CORP CLASS A", "weight": 0.02, "price": 362.60},
    {"ticker": "RVTY", "name": "REVVITY INC", "weight": 0.02, "price": 98.31},
    {"ticker": "SJM", "name": "JM SMUCKER", "weight": 0.02, "price": 115.95},
    {"ticker": "SOLV", "name": "SOLVENTUM CORP", "weight": 0.02, "price": 74.20},
    {"ticker": "SWK", "name": "STANLEY BLACK & DECKER INC", "weight": 0.02, "price": 86.49},
    {"ticker": "SWKS", "name": "SKYWORKS SOLUTIONS INC", "weight": 0.02, "price": 59.58},
    {"ticker": "TECH", "name": "BIO TECHNE CORP", "weight": 0.02, "price": 59.00},
    {"ticker": "TTD", "name": "TRADE DESK INC CLASS A", "weight": 0.02, "price": 23.82},
    {"ticker": "UDR", "name": "UDR REIT INC", "weight": 0.02, "price": 37.50},
    {"ticker": "UHS", "name": "UNIVERSAL HEALTH SERVICES INC CLAS", "weight": 0.02, "price": 205.90},
    {"ticker": "WYNN", "name": "WYNN RESORTS LTD", "weight": 0.02, "price": 108.19},
    {"ticker": "ZBRA", "name": "ZEBRA TECHNOLOGIES CORP CLASS A", "weight": 0.02, "price": 223.96},
    {"ticker": "ARE", "name": "ALEXANDRIA REAL ESTATE EQUITIES RE", "weight": 0.01, "price": 54.04},
    {"ticker": "BEN", "name": "FRANKLIN RESOURCES INC", "weight": 0.01, "price": 26.54},
    {"ticker": "BFB", "name": "BROWN FORMAN CORP CLASS B", "weight": 0.01, "price": 28.86},
    {"ticker": "BXP", "name": "BXP INC", "weight": 0.01, "price": 57.58},
    {"ticker": "CPB", "name": "CAMPBELL SOUP", "weight": 0.01, "price": 26.95},
    {"ticker": "CRL", "name": "CHARLES RIVER LABORATORIES INTERNA", "weight": 0.01, "price": 178.49},
    {"ticker": "DVA", "name": "DAVITA INC", "weight": 0.01, "price": 156.30},
    {"ticker": "EPAM", "name": "EPAM SYSTEMS INC", "weight": 0.01, "price": 141.00},
    {"ticker": "ERIE", "name": "ERIE INDEMNITY CLASS A", "weight": 0.01, "price": 269.44},
    {"ticker": "FDS", "name": "FACTSET RESEARCH SYSTEMS INC", "weight": 0.01, "price": 216.81},
    {"ticker": "FOX", "name": "FOX CORP CLASS B", "weight": 0.01, "price": 51.73},
    {"ticker": "FRT", "name": "FEDERAL REALTY INVESTMENT TRUST RE", "weight": 0.01, "price": 108.77},
    {"ticker": "HRL", "name": "HORMEL FOODS CORP", "weight": 0.01, "price": 25.60},
    {"ticker": "HSIC", "name": "HENRY SCHEIN INC", "weight": 0.01, "price": 82.39},
    {"ticker": "LW", "name": "LAMB WESTON HOLDINGS INC", "weight": 0.01, "price": 48.19},
    {"ticker": "MGM", "name": "MGM RESORTS INTERNATIONAL", "weight": 0.01, "price": 36.86},
    {"ticker": "MOH", "name": "MOLINA HEALTHCARE INC", "weight": 0.01, "price": 154.05},
    {"ticker": "MTCH", "name": "MATCH GROUP INC", "weight": 0.01, "price": 31.60},
    {"ticker": "NWS", "name": "NEWS CORP CLASS B", "weight": 0.01, "price": 26.78},
    {"ticker": "PAYC", "name": "PAYCOM SOFTWARE INC", "weight": 0.01, "price": 125.83},
    {"ticker": "POOL", "name": "POOL CORP", "weight": 0.01, "price": 227.18},
    {"ticker": "PSKY", "name": "PARAMOUNT SKYDANCE CORP CLASS B", "weight": 0.01, "price": 13.51},
    {"ticker": "TAP", "name": "MOLSON COORS BREWING CLASS B", "weight": 0.01, "price": 48.99},
]

NDX_DATA = [
    {"ticker": "NVDA", "name": "NVIDIA CORP", "weight": 8.4, "price": 177.19},
    {"ticker": "AAPL", "name": "APPLE INC", "weight": 7.61, "price": 264.18},
    {"ticker": "MSFT", "name": "MICROSOFT CORP", "weight": 5.69, "price": 392.74},
    {"ticker": "AMZN", "name": "AMAZON COM INC", "weight": 4.38, "price": 210.00},
    {"ticker": "TSLA", "name": "TESLA INC", "weight": 3.92, "price": 402.51},
    {"ticker": "META", "name": "META PLATFORMS INC CLASS A", "weight": 3.71, "price": 648.18},
    {"ticker": "GOOGL", "name": "ALPHABET INC CLASS A", "weight": 3.54, "price": 311.76},
    {"ticker": "WMT", "name": "WALMART INC", "weight": 3.37, "price": 127.95},
    {"ticker": "GOOG", "name": "ALPHABET INC CLASS C", "weight": 3.28, "price": 311.43},
    {"ticker": "AVGO", "name": "BROADCOM INC", "weight": 2.94, "price": 319.55},
    {"ticker": "MU", "name": "MICRON TECHNOLOGY INC", "weight": 2.5, "price": 412.37},
    {"ticker": "COST", "name": "COSTCO WHOLESALE CORP", "weight": 2.41, "price": 1010.79},
    {"ticker": "NFLX", "name": "NETFLIX INC", "weight": 2.19, "price": 96.24},
    {"ticker": "AMD", "name": "ADVANCED MICRO DEVICES INC", "weight": 1.76, "price": 200.21},
    {"ticker": "CSCO", "name": "CISCO SYSTEMS INC", "weight": 1.69, "price": 79.46},
    {"ticker": "PLTR", "name": "PALANTIR TECHNOLOGIES INC CLASS A", "weight": 1.69, "price": 137.19},
    {"ticker": "AMAT", "name": "APPLIED MATERIAL INC", "weight": 1.59, "price": 372.30},
    {"ticker": "LRCX", "name": "LAM RESEARCH CORP", "weight": 1.58, "price": 233.89},
    {"ticker": "TMUS", "name": "T MOBILE US INC", "weight": 1.31, "price": 217.09},
    {"ticker": "LIN", "name": "LINDE PLC", "weight": 1.28, "price": 508.08},
    {"ticker": "PEP", "name": "PEPSICO INC", "weight": 1.25, "price": 169.74},
    {"ticker": "INTC", "name": "INTEL CORPORATION CORP", "weight": 1.17, "price": 45.61},
    {"ticker": "AMGN", "name": "AMGEN INC", "weight": 1.13, "price": 388.16},
    {"ticker": "KLAC", "name": "KLA CORP", "weight": 1.08, "price": 1524.55},
    {"ticker": "TXN", "name": "TEXAS INSTRUMENT INC", "weight": 1.04, "price": 212.11},
    {"ticker": "GILD", "name": "GILEAD SCIENCES INC", "weight": 1, "price": 148.95},
    {"ticker": "ISRG", "name": "INTUITIVE SURGICAL INC", "weight": 0.96, "price": 503.51},
    {"ticker": "ADI", "name": "ANALOG DEVICES INC", "weight": 0.94, "price": 355.79},
    {"ticker": "HON", "name": "HONEYWELL INTERNATIONAL INC", "weight": 0.83, "price": 243.59},
    {"ticker": "QCOM", "name": "QUALCOMM INC", "weight": 0.82, "price": 142.36},
    {"ticker": "SHOP", "name": "SHOPIFY SUBORDINATE VOTING INC CLA", "weight": 0.79, "price": 120.73},
    {"ticker": "BKNG", "name": "BOOKING HOLDINGS INC", "weight": 0.73, "price": 4239.35},
    {"ticker": "APP", "name": "APPLOVIN CORP CLASS A", "weight": 0.72, "price": 434.77},
    {"ticker": "ASML", "name": "ASML HOLDING ADR REPRESENTING NV", "weight": 0.69, "price": 1450.56},
    {"ticker": "VRTX", "name": "VERTEX PHARMACEUTICALS INC", "weight": 0.68, "price": 496.83},
    {"ticker": "PANW", "name": "PALO ALTO NETWORKS INC", "weight": 0.65, "price": 148.92},
    {"ticker": "CEG", "name": "CONSTELLATION ENERGY CORP", "weight": 0.64, "price": 329.88},
    {"ticker": "INTU", "name": "INTUIT INC", "weight": 0.61, "price": 409.03},
    {"ticker": "CMCSA", "name": "COMCAST CORP CLASS A", "weight": 0.6, "price": 30.96},
    {"ticker": "SBUX", "name": "STARBUCKS CORP", "weight": 0.6, "price": 98.02},
    {"ticker": "ADBE", "name": "ADOBE INC", "weight": 0.59, "price": 262.41},
    {"ticker": "WDC", "name": "WESTERN DIGITAL CORP", "weight": 0.51, "price": 279.70},
    {"ticker": "CRWD", "name": "CROWDSTRIKE HOLDINGS INC CLASS A", "weight": 0.5, "price": 371.98},
    {"ticker": "MAR", "name": "MARRIOTT INTERNATIONAL INC CLASS A", "weight": 0.49, "price": 341.73},
    {"ticker": "MELI", "name": "MERCADOLIBRE INC", "weight": 0.48, "price": 1757.58},
    {"ticker": "STX", "name": "SEAGATE TECHNOLOGY HOLDINGS PLC", "weight": 0.47, "price": 407.84},
    {"ticker": "ADP", "name": "AUTOMATIC DATA PROCESSING INC", "weight": 0.46, "price": 214.36},
    {"ticker": "MNST", "name": "MONSTER BEVERAGE CORP", "weight": 0.45, "price": 85.30},
    {"ticker": "CDNS", "name": "CADENCE DESIGN SYSTEMS INC", "weight": 0.44, "price": 301.40},
    {"ticker": "CTAS", "name": "CINTAS CORP", "weight": 0.44, "price": 201.13},
    {"ticker": "CSX", "name": "CSX CORP", "weight": 0.43, "price": 42.69},
    {"ticker": "MDLZ", "name": "MONDELEZ INTERNATIONAL INC CLASS A", "weight": 0.43, "price": 61.58},
    {"ticker": "ORLY", "name": "OREILLY AUTOMOTIVE INC", "weight": 0.43, "price": 93.88},
    {"ticker": "REGN", "name": "REGENERON PHARMACEUTICALS INC", "weight": 0.43, "price": 781.67},
    {"ticker": "SNPS", "name": "SYNOPSYS INC", "weight": 0.42, "price": 414.00},
    {"ticker": "DASH", "name": "DOORDASH INC CLASS A", "weight": 0.39, "price": 176.47},
    {"ticker": "AEP", "name": "AMERICAN ELECTRIC POWER INC", "weight": 0.38, "price": 133.82},
    {"ticker": "MRVL", "name": "MARVELL TECHNOLOGY INC", "weight": 0.38, "price": 81.69},
    {"ticker": "PDD", "name": "PDD HOLDINGS ADS INC", "weight": 0.37, "price": 103.73},
    {"ticker": "WBD", "name": "WARNER BROS. DISCOVERY INC SERIES", "weight": 0.37, "price": 28.17},
    {"ticker": "ROST", "name": "ROSS STORES INC", "weight": 0.36, "price": 205.64},
    {"ticker": "PCAR", "name": "PACCAR INC", "weight": 0.35, "price": 126.09},
    {"ticker": "BKR", "name": "BAKER HUGHES CLASS A", "weight": 0.34, "price": 65.26},
    {"ticker": "FTNT", "name": "FORTINET INC", "weight": 0.32, "price": 79.03},
    {"ticker": "ABNB", "name": "AIRBNB INC CLASS A", "weight": 0.31, "price": 135.11},
    {"ticker": "NXPI", "name": "NXP SEMICONDUCTORS NV", "weight": 0.31, "price": 227.01},
    {"ticker": "FAST", "name": "FASTENAL", "weight": 0.29, "price": 46.04},
    {"ticker": "FER", "name": "FERROVIAL", "weight": 0.29, "price": 74.38},
    {"ticker": "MPWR", "name": "MONOLITHIC POWER SYSTEMS INC", "weight": 0.29, "price": 1142.74},
    {"ticker": "ADSK", "name": "AUTODESK INC", "weight": 0.28, "price": 245.87},
    {"ticker": "IDXX", "name": "IDEXX LABORATORIES INC", "weight": 0.28, "price": 656.73},
    {"ticker": "CCEP", "name": "COCA COLA EUROPACIFIC PARTNERS PLC", "weight": 0.27, "price": 110.43},
    {"ticker": "EA", "name": "ELECTRONIC ARTS INC", "weight": 0.27, "price": 200.57},
    {"ticker": "EXC", "name": "EXELON CORP", "weight": 0.27, "price": 49.05},
    {"ticker": "FANG", "name": "DIAMONDBACK ENERGY INC", "weight": 0.27, "price": 174.08},
    {"ticker": "XEL", "name": "XCEL ENERGY INC", "weight": 0.27, "price": 83.36},
    {"ticker": "ALNY", "name": "ALNYLAM PHARMACEUTICALS INC", "weight": 0.24, "price": 332.92},
    {"ticker": "AXON", "name": "AXON ENTERPRISE INC", "weight": 0.23, "price": 542.40},
    {"ticker": "ODFL", "name": "OLD DOMINION FREIGHT LINE INC", "weight": 0.23, "price": 203.05},
    {"ticker": "PYPL", "name": "PAYPAL HOLDINGS INC", "weight": 0.23, "price": 46.21},
    {"ticker": "TRI", "name": "THOMSON REUTERS CORP", "weight": 0.23, "price": 96.41},
    {"ticker": "KDP", "name": "KEURIG DR PEPPER INC", "weight": 0.22, "price": 30.28},
    {"ticker": "MCHP", "name": "MICROCHIP TECHNOLOGY INC", "weight": 0.22, "price": 74.64},
    {"ticker": "GEHC", "name": "GE HEALTHCARE TECHNOLOGIES INC", "weight": 0.21, "price": 84.27},
    {"ticker": "TTWO", "name": "TAKE TWO INTERACTIVE SOFTWARE INC", "weight": 0.21, "price": 211.48},
    {"ticker": "CPRT", "name": "COPART INC", "weight": 0.2, "price": 38.09},
    {"ticker": "DDOG", "name": "DATADOG INC CLASS A", "weight": 0.2, "price": 111.96},
    {"ticker": "ROP", "name": "ROPER TECHNOLOGIES INC", "weight": 0.2, "price": 349.73},
    {"ticker": "MSTR", "name": "STRATEGY INC CLASS A", "weight": 0.19, "price": 129.50},
    {"ticker": "PAYX", "name": "PAYCHEX INC", "weight": 0.18, "price": 93.65},
    {"ticker": "CTSH", "name": "COGNIZANT TECHNOLOGY SOLUTIONS COR", "weight": 0.17, "price": 64.43},
    {"ticker": "INSM", "name": "INSMED INC", "weight": 0.17, "price": 149.33},
    {"ticker": "CHTR", "name": "CHARTER COMMUNICATIONS INC CLASS A", "weight": 0.16, "price": 234.63},
    {"ticker": "KHC", "name": "KRAFT HEINZ", "weight": 0.16, "price": 24.61},
    {"ticker": "VRSK", "name": "VERISK ANALYTICS INC", "weight": 0.16, "price": 207.57},
    {"ticker": "DXCM", "name": "DEXCOM INC", "weight": 0.15, "price": 73.43},
    {"ticker": "WDAY", "name": "WORKDAY INC CLASS A", "weight": 0.15, "price": 133.76},
    {"ticker": "ZS", "name": "ZSCALER INC", "weight": 0.13, "price": 146.99},
    {"ticker": "CSGP", "name": "COSTAR GROUP INC", "weight": 0.1, "price": 44.63},
    {"ticker": "ARM", "name": "ARM HOLDINGS AMERICAN DEPOSITARY S", "weight": 0.09, "price": 127.45},
    {"ticker": "TEAM", "name": "ATLASSIAN CORP CLASS A", "weight": 0.07, "price": 75.13},
]
